### ISSUE TITLE
Color weaving in Vega

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#185] opened 2023-06-21 22:54 UTC

**Comment by JosephCottam** [comment] 2023-07-13 14:15
Vega does not support textures in fills natively.  The root of the issue is that the want to use both an SVG and an HTML Canvas back-end and those two back-ends treat textures very differently.  

There is a [work-around on the SVG](https://observablehq.com/@oliviafvane/how-to-use-textures-patterns-in-vega-lite) version involving textures defined in the same HTML page and referred to with a URI. 

Using this a URI-based pattern changes what we would need to pass to the HMI team.  Currently it is just a vega spec.  We would need to return an HTML page with the spec and the patterns or a pair of spec+things-to-embed-in-something-like-an-html-page.  This could be a nice task, but a low priority.

**Comment by SamWitty** [comment] 2024-02-14 21:54
Closing. See discussion in #51 .

**Closed by SamWitty** 2024-02-14 21:54 UTC
Labels: enhancement
